# -*- coding: utf-8 -*-
"""Logistic Regression.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1s_F_oZ4I-lrLZJ13h8egtJhki1G1Tn-G
"""

import pandas as pd
import numpy as np
import matplotlib as mpl
import matplotlib.pyplot as plt

from scipy.optimize import minimize

from sklearn.preprocessing import PolynomialFeatures

pd.set_option('display.notebook_repr_html', False)
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', 150)
pd.set_option('display.max_seq_items', None)
 
#%config InlineBackend.figure_formats = {'pdf',}
# %matplotlib inline
from google.colab import files

import seaborn as sns
sns.set_context('notebook')
sns.set_style('white')
uploaded = files.upload()

#Load Data
data = np.loadtxt('ex2data1.txt', delimiter=",")

def plotData(data, label_x, label_y, label_pos, label_neg, axes=None):
  
    # Get indexes for class 0 and class 1
    neg = data[:,2] == 0
    pos = data[:,2] == 1
    
    # If no specific axes object has been passed, get the current axes.
    if axes == None:
        axes = plt.gca()
    axes.scatter(data[pos][:,0], data[pos][:,1], marker='+', c='k', s=60, linewidth=2, label=label_pos)
    axes.scatter(data[neg][:,0], data[neg][:,1], c='y', s=60, label=label_neg)
    axes.set_xlabel(label_x)
    axes.set_ylabel(label_y)
    axes.legend(frameon= True, fancybox = True);

#Add the collumn of ones and get it into X
X = np.c_[np.ones((data.shape[0],1)), data[:,0:2]]

#fethch the given prediction
y = np.c_[data[:,2]]

plotData(data, 'Exam 1 score', 'Exam 2 score', 'Admitted', 'Not admitted')

#Evaluate sigmoid
def sigmoid(z):
    return(1 / (1 + np.exp(-z)))

#compute cost
def costFunction(theta, X, y):
    m = y.size
    h = sigmoid(X.dot(theta))
    
    J = -1*(1/m)*(np.log(h).T.dot(y)+np.log(1-h).T.dot(1-y))
               
    if np.isnan(J[0]):
        return(np.inf)
    return(J[0])

#compute gradient Descent
def gradient(theta, X, y):
    m = y.size
    h = sigmoid(X.dot(theta.reshape(-1,1)))
    
    grad =(1/m)*X.T.dot(h-y)

    return(grad.flatten())

#initilize theta with 0
initial_theta = np.zeros(X.shape[1])

#cost with initial theta
cost = costFunction(initial_theta, X, y)
print('Cost: \n', cost)

#gradient Descent with initial theta
grad = gradient(initial_theta, X, y)

print('Grad: \n', grad)

#Declare the theta for test
test_theta = np.array([-24, 0.2, 0.2])

cost = costFunction(test_theta, X, y)
print('Cost: \n', cost)

grad = gradient(test_theta, X, y)
print('Grad: \n', grad)

res = minimize(costFunction, initial_theta, args=(X,y), method=None, jac=gradient, options={'maxiter':400})
res

def predict(theta, X, threshold=0.5):
    p = sigmoid(X.dot(theta.T)) >= threshold
    return(p.astype('int'))

# Student with Exam 1 score 45 and Exam 2 score 85
# Predict using the optimized Theta values from above (res.x)
sigmoid(np.array([1, 45, 85]).dot(res.x.T))

p = predict(res.x, X) 
print('Train accuracy {}%'.format(100*sum(p == y.ravel())/p.size))

"""#### Decision boundary"""

plotData(data, 'Exam 1 score', 'Exam 2 score', 'Admitted', 'Not admitted')

#find max and min of both exam score to generate the meshgrid
x1_min, x1_max = X[:,1].min(), X[:,1].max(),
x2_min, x2_max = X[:,2].min(), X[:,2].max(),

#generate the meshgrid
xx1, xx2 = np.meshgrid(np.linspace(x1_min, x1_max), np.linspace(x2_min, x2_max))

#find the hypothesis
h = sigmoid(np.c_[np.ones((xx1.ravel().shape[0],1)), xx1.ravel(), xx2.ravel()].dot(res.x))
h = h.reshape(xx1.shape)

#plot the decision boundry
plt.contour(xx1, xx2, h, [0.5], linewidths=1, colors='b');

"""### Regularized logistic regression"""

data2 = np.loadtxt('ex2data2.txt', delimiter=",")

y = np.c_[data2[:,2]]
X = data2[:,0:2]

plotData(data2, 'Microchip Test 1', 'Microchip Test 2', 'y = 1', 'y = 0')

"""#### Polynomials"""

# Note that this function inserts a column with 'ones' in the design matrix for the intercept.
poly = PolynomialFeatures(6)
XX = poly.fit_transform(data2[:,0:2])
XX.shape

def costFunctionReg(theta, reg, *args):
    m = y.size
    h = sigmoid(XX.dot(theta))
    
    J = -1*(1/m)*(np.log(h).T.dot(y)+np.log(1-h).T.dot(1-y)) + (reg/(2*m))*np.sum(np.square(theta[1:]))
    
    if np.isnan(J[0]):
        return(np.inf)
    return(J[0])

def gradientReg(theta, reg, *args):
    m = y.size
    h = sigmoid(XX.dot(theta.reshape(-1,1)))
      
    grad = (1/m)*XX.T.dot(h-y) + (reg/m)*np.r_[[[0]],theta[1:].reshape(-1,1)]
        
    return(grad.flatten())

#Compute and display initial cost and gradient for regularized logistic regression
initial_theta = np.zeros(XX.shape[1])
cost_reg = costFunctionReg(initial_theta, 1, XX, y)
print(cost_reg)

#Gradient at initial theta (zeros) - first five values only:
gradReg = gradientReg(initial_theta, 1, XX, y)
print(gradReg[0:5])

#Compute and display cost and gradient with all-ones theta and lambda = 10
test_theta = np.ones(XX.shape[1]);
#Cost at test_theta
initial_theta = np.zeros(XX.shape[1])
costReg = costFunctionReg(test_theta, 10, XX, yy)
print(costReg)

#Gradient at test_theta (lamda = 10) - first five values only:
gradReg = gradientReg(test_theta, 10, XX, yy)
print(gradReg[0:5])

fig, axes = plt.subplots(1,3, sharey = True, figsize=(17,5))

# Decision boundaries
# Lambda = 0 : No regularization --> too flexible, overfitting the training data
# Lambda = 1 : Looks about right
# Lambda = 100 : Too much regularization --> high bias

for i, C in enumerate([0, 1, 100]):
    # Optimize costFunctionReg
    
    res2 = minimize(costFunctionReg, initial_theta, args=(C, XX, y), method=None, jac=gradientReg, options={'maxiter':3000})
    
    # Accuracy
    accuracy = 100*sum(predict(res2.x, XX) == y.ravel())/y.size    

    # Scatter plot of X,y
    plotData(data2, 'Microchip Test 1', 'Microchip Test 2', 'y = 1', 'y = 0', axes.flatten()[i])
    
    #Plot decisionboundary
    x1_min, x1_max = X[:,0].min(), X[:,0].max(),
    x2_min, x2_max = X[:,1].min(), X[:,1].max(),
    xx1, xx2 = np.meshgrid(np.linspace(x1_min, x1_max), np.linspace(x2_min, x2_max))
    h = sigmoid(poly.fit_transform(np.c_[xx1.ravel(), xx2.ravel()]).dot(res2.x))
    h = h.reshape(xx1.shape)
    axes.flatten()[i].contour(xx1, xx2, h, [0.5], linewidths=1, colors='g');       
    axes.flatten()[i].set_title('Train accuracy {}% with Lambda = {}'.format(np.round(accuracy, decimals=2), C))



